dataSources:
  member_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo1;INIT=RUNSCRIPT FROM 'classpath:db/init-shardingdemo1.sql';MODE=MYSQL
    username: root
    password: sa
  member_slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo2;INIT=RUNSCRIPT FROM 'classpath:db/init-shardingdemo1.sql';MODE=MYSQL
    username: root
    password: sa
  info_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo3;INIT=RUNSCRIPT FROM 'classpath:db/init-shardingdemo2.sql';MODE=MYSQL
    username: root
    password: sa
  info_slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo4;INIT=RUNSCRIPT FROM 'classpath:db/init-shardingdemo2.sql';MODE=MYSQL
    username: root
    password: sa
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_member:
      writeDataSourceName: member_master
      readDataSourceNames:
        - member_slave
      loadBalancerName: round_robin
    readwrite_info:
      writeDataSourceName: info_master
      readDataSourceNames:
        - info_slave
      loadBalancerName: round_robin
  loadBalancers:
    round_robin:
      type: ROUND_ROBIN
- !SINGLE
  tables:
    - "*.*"

sqlFederation:
  sqlFederationEnabled: true
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535

props:
  sql-show: true

