dataSources:
  member_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo1;INIT=RUNSCRIPT FROM 'classpath:db/init-shardingdemo1.sql';MODE=MYSQL
    username: root
    password: sa
  member_slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo1;MODE=MYSQL
    username: root
    password: sa
  info_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo2;INIT=RUNSCRIPT FROM 'classpath:db/init-shardingdemo2.sql';MODE=MYSQL
    username: root
    password: sa
  info_slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:shardingdemo2;MODE=MYSQL
    username: root
    password: sa
rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_member:
        staticStrategy:
          writeDataSourceName: member_master
          readDataSourceNames:
            - member_slave
        loadBalancerName: round_robin
      readwrite_info:
        staticStrategy:
          writeDataSourceName: info_master
          readDataSourceNames:
            - info_slave
        loadBalancerName: round_robin
    loadBalancers:
      round_robin:
        type: ROUND_ROBIN


props:
  sql-show: true
  sql-federation-type: ORIGINAL

